import {
  Property,
  Account,
  Statement,
  Transaction,
  CategoryBreakdown,
  MonthlySummary,
} from "./types";
import { EXPENSE_CATEGORIES } from "./constants/categories";

const MOCK_USER_ID = "mock-user-1";

export const properties: Property[] = [
  {
    id: "prop-1",
    userId: MOCK_USER_ID,
    name: "Maple Street Duplex",
    address: "142 Maple St, Austin, TX 78701",
    units: 2,
    createdAt: "2025-12-01T00:00:00Z",
  },
  {
    id: "prop-2",
    userId: MOCK_USER_ID,
    name: "Oakwood Apartments",
    address: "890 Oakwood Dr, Austin, TX 78704",
    units: 4,
    createdAt: "2025-12-01T00:00:00Z",
  },
  {
    id: "prop-3",
    userId: MOCK_USER_ID,
    name: "Pine Ridge House",
    address: "55 Pine Ridge Ln, Round Rock, TX 78664",
    units: 1,
    createdAt: "2025-12-01T00:00:00Z",
  },
];

export const accounts: Account[] = [
  {
    id: "acct-1",
    userId: MOCK_USER_ID,
    name: "Maple St Operating",
    type: "checking",
    lastFour: "4821",
    propertyId: "prop-1",
    createdAt: "2025-12-01T00:00:00Z",
  },
  {
    id: "acct-2",
    userId: MOCK_USER_ID,
    name: "Maple St Reserves",
    type: "savings",
    lastFour: "7733",
    propertyId: "prop-1",
    createdAt: "2025-12-01T00:00:00Z",
  },
  {
    id: "acct-3",
    userId: MOCK_USER_ID,
    name: "Oakwood Operating",
    type: "checking",
    lastFour: "1156",
    propertyId: "prop-2",
    createdAt: "2025-12-01T00:00:00Z",
  },
  {
    id: "acct-4",
    userId: MOCK_USER_ID,
    name: "Oakwood Credit",
    type: "credit",
    lastFour: "9042",
    propertyId: "prop-2",
    createdAt: "2025-12-01T00:00:00Z",
  },
  {
    id: "acct-5",
    userId: MOCK_USER_ID,
    name: "Pine Ridge Operating",
    type: "checking",
    lastFour: "3389",
    propertyId: "prop-3",
    createdAt: "2025-12-01T00:00:00Z",
  },
];

export const statements: Statement[] = [
  {
    id: "stmt-1",
    userId: MOCK_USER_ID,
    accountId: "acct-1",
    month: 2,
    year: 2026,
    status: "processed",
    transactionCount: 12,
    uploadedAt: "2026-03-05T10:30:00Z",
    fileName: "maple_st_feb_2026.pdf",
  },
  {
    id: "stmt-2",
    userId: MOCK_USER_ID,
    accountId: "acct-3",
    month: 2,
    year: 2026,
    status: "processed",
    transactionCount: 8,
    uploadedAt: "2026-03-06T14:15:00Z",
    fileName: "oakwood_feb_2026.pdf",
  },
  {
    id: "stmt-3",
    userId: MOCK_USER_ID,
    accountId: "acct-5",
    month: 2,
    year: 2026,
    status: "pending",
    transactionCount: 5,
    uploadedAt: "2026-03-10T09:00:00Z",
    fileName: "pine_ridge_feb_2026.csv",
  },
  {
    id: "stmt-4",
    userId: MOCK_USER_ID,
    accountId: "acct-1",
    month: 1,
    year: 2026,
    status: "processed",
    transactionCount: 10,
    uploadedAt: "2026-02-04T11:20:00Z",
    fileName: "maple_st_jan_2026.pdf",
  },
  {
    id: "stmt-5",
    userId: MOCK_USER_ID,
    accountId: "acct-3",
    month: 1,
    year: 2026,
    status: "processed",
    transactionCount: 9,
    uploadedAt: "2026-02-05T16:45:00Z",
    fileName: "oakwood_jan_2026.pdf",
  },
  {
    id: "stmt-6",
    userId: MOCK_USER_ID,
    accountId: "acct-4",
    month: 1,
    year: 2026,
    status: "error",
    transactionCount: 0,
    uploadedAt: "2026-02-05T16:50:00Z",
    fileName: "oakwood_credit_jan_2026.pdf",
  },
];

export const transactions: Transaction[] = [
  {
    id: "txn-1",
    userId: MOCK_USER_ID,
    statementId: "stmt-1",
    accountId: "acct-1",
    propertyId: "prop-1",
    date: "2026-02-01",
    description: "First National Mortgage Payment",
    amount: -1850.0,
    direction: "debit",
    suggestedCategory: "Mortgage",
    finalCategory: "Mortgage",
    confidence: 0.98,
    needsReview: false,
    createdAt: "2026-03-05T10:30:00Z",
  },
  {
    id: "txn-2",
    userId: MOCK_USER_ID,
    statementId: "stmt-1",
    accountId: "acct-1",
    propertyId: "prop-1",
    date: "2026-02-03",
    description: "Tenant A - Rent Deposit",
    amount: 1400.0,
    direction: "credit",
    suggestedCategory: "Rental Income",
    finalCategory: "Rental Income",
    confidence: 0.95,
    needsReview: false,
    createdAt: "2026-03-05T10:30:00Z",
  },
  {
    id: "txn-3",
    userId: MOCK_USER_ID,
    statementId: "stmt-1",
    accountId: "acct-1",
    propertyId: "prop-1",
    date: "2026-02-03",
    description: "Tenant B - Rent Deposit",
    amount: 1350.0,
    direction: "credit",
    suggestedCategory: "Rental Income",
    finalCategory: "Rental Income",
    confidence: 0.95,
    needsReview: false,
    createdAt: "2026-03-05T10:30:00Z",
  },
  {
    id: "txn-4",
    userId: MOCK_USER_ID,
    statementId: "stmt-1",
    accountId: "acct-1",
    propertyId: "prop-1",
    date: "2026-02-07",
    description: "Austin Energy - Electric",
    amount: -245.3,
    direction: "debit",
    suggestedCategory: "Utilities",
    finalCategory: "Utilities",
    confidence: 0.92,
    needsReview: false,
    createdAt: "2026-03-05T10:30:00Z",
  },
  {
    id: "txn-5",
    userId: MOCK_USER_ID,
    statementId: "stmt-1",
    accountId: "acct-1",
    propertyId: "prop-1",
    date: "2026-02-10",
    description: "Ace Hardware - Supplies",
    amount: -87.42,
    direction: "debit",
    suggestedCategory: "Repairs & Maintenance",
    finalCategory: "Repairs & Maintenance",
    confidence: 0.72,
    needsReview: true,
    createdAt: "2026-03-05T10:30:00Z",
  },
  {
    id: "txn-6",
    userId: MOCK_USER_ID,
    statementId: "stmt-1",
    accountId: "acct-1",
    propertyId: "prop-1",
    date: "2026-02-12",
    description: "Home Depot #4521",
    amount: -312.99,
    direction: "debit",
    suggestedCategory: "Repairs & Maintenance",
    finalCategory: "Repairs & Maintenance",
    confidence: 0.65,
    needsReview: true,
    createdAt: "2026-03-05T10:30:00Z",
  },
  {
    id: "txn-7",
    userId: MOCK_USER_ID,
    statementId: "stmt-1",
    accountId: "acct-1",
    propertyId: "prop-1",
    date: "2026-02-15",
    description: "State Farm Insurance - Monthly",
    amount: -189.0,
    direction: "debit",
    suggestedCategory: "Insurance",
    finalCategory: "Insurance",
    confidence: 0.97,
    needsReview: false,
    createdAt: "2026-03-05T10:30:00Z",
  },
  {
    id: "txn-8",
    userId: MOCK_USER_ID,
    statementId: "stmt-1",
    accountId: "acct-1",
    propertyId: "prop-1",
    date: "2026-02-18",
    description: "Transfer to Savings",
    amount: -500.0,
    direction: "debit",
    suggestedCategory: "Miscellaneous",
    finalCategory: "Miscellaneous",
    confidence: 0.45,
    needsReview: true,
    createdAt: "2026-03-05T10:30:00Z",
  },
  {
    id: "txn-9",
    userId: MOCK_USER_ID,
    statementId: "stmt-2",
    accountId: "acct-3",
    propertyId: "prop-2",
    date: "2026-02-01",
    description: "Chase Mortgage - Oakwood",
    amount: -3200.0,
    direction: "debit",
    suggestedCategory: "Mortgage",
    finalCategory: "Mortgage",
    confidence: 0.97,
    needsReview: false,
    createdAt: "2026-03-06T14:15:00Z",
  },
  {
    id: "txn-10",
    userId: MOCK_USER_ID,
    statementId: "stmt-2",
    accountId: "acct-3",
    propertyId: "prop-2",
    date: "2026-02-02",
    description: "Unit 1 Rent - Johnson",
    amount: 1200.0,
    direction: "credit",
    suggestedCategory: "Rental Income",
    finalCategory: "Rental Income",
    confidence: 0.93,
    needsReview: false,
    createdAt: "2026-03-06T14:15:00Z",
  },
  {
    id: "txn-11",
    userId: MOCK_USER_ID,
    statementId: "stmt-2",
    accountId: "acct-3",
    propertyId: "prop-2",
    date: "2026-02-02",
    description: "Unit 2 Rent - Williams",
    amount: 1200.0,
    direction: "credit",
    suggestedCategory: "Rental Income",
    finalCategory: "Rental Income",
    confidence: 0.93,
    needsReview: false,
    createdAt: "2026-03-06T14:15:00Z",
  },
  {
    id: "txn-12",
    userId: MOCK_USER_ID,
    statementId: "stmt-2",
    accountId: "acct-3",
    propertyId: "prop-2",
    date: "2026-02-05",
    description: "Greenscape Landscaping",
    amount: -350.0,
    direction: "debit",
    suggestedCategory: "Landscaping",
    finalCategory: "Landscaping",
    confidence: 0.78,
    needsReview: true,
    createdAt: "2026-03-06T14:15:00Z",
  },
  {
    id: "txn-13",
    userId: MOCK_USER_ID,
    statementId: "stmt-2",
    accountId: "acct-3",
    propertyId: "prop-2",
    date: "2026-02-08",
    description: "Oakwood HOA February",
    amount: -275.0,
    direction: "debit",
    suggestedCategory: "HOA",
    finalCategory: "HOA",
    confidence: 0.96,
    needsReview: false,
    createdAt: "2026-03-06T14:15:00Z",
  },
  {
    id: "txn-14",
    userId: MOCK_USER_ID,
    statementId: "stmt-2",
    accountId: "acct-3",
    propertyId: "prop-2",
    date: "2026-02-14",
    description: "Amazon - Door Lock Set",
    amount: -129.99,
    direction: "debit",
    suggestedCategory: "Supplies",
    finalCategory: "Supplies",
    confidence: 0.58,
    needsReview: true,
    createdAt: "2026-03-06T14:15:00Z",
  },
  {
    id: "txn-15",
    userId: MOCK_USER_ID,
    statementId: "stmt-2",
    accountId: "acct-3",
    propertyId: "prop-2",
    date: "2026-02-20",
    description: "Travis County Tax Collector",
    amount: -1450.0,
    direction: "debit",
    suggestedCategory: "Property Tax",
    finalCategory: "Property Tax",
    confidence: 0.94,
    needsReview: false,
    createdAt: "2026-03-06T14:15:00Z",
  },
  {
    id: "txn-16",
    userId: MOCK_USER_ID,
    statementId: "stmt-3",
    accountId: "acct-5",
    propertyId: "prop-3",
    date: "2026-02-01",
    description: "Wells Fargo Mortgage",
    amount: -1100.0,
    direction: "debit",
    suggestedCategory: "Mortgage",
    finalCategory: "Mortgage",
    confidence: 0.96,
    needsReview: false,
    createdAt: "2026-03-10T09:00:00Z",
  },
  {
    id: "txn-17",
    userId: MOCK_USER_ID,
    statementId: "stmt-3",
    accountId: "acct-5",
    propertyId: "prop-3",
    date: "2026-02-03",
    description: "Rent Payment - Garcia",
    amount: 1500.0,
    direction: "credit",
    suggestedCategory: "Rental Income",
    finalCategory: "Rental Income",
    confidence: 0.94,
    needsReview: false,
    createdAt: "2026-03-10T09:00:00Z",
  },
  {
    id: "txn-18",
    userId: MOCK_USER_ID,
    statementId: "stmt-3",
    accountId: "acct-5",
    propertyId: "prop-3",
    date: "2026-02-11",
    description: "Roto-Rooter Plumbing",
    amount: -425.0,
    direction: "debit",
    suggestedCategory: "Repairs & Maintenance",
    finalCategory: "Repairs & Maintenance",
    confidence: 0.88,
    needsReview: false,
    createdAt: "2026-03-10T09:00:00Z",
  },
  {
    id: "txn-19",
    userId: MOCK_USER_ID,
    statementId: "stmt-3",
    accountId: "acct-5",
    propertyId: "prop-3",
    date: "2026-02-16",
    description: "Venmo Payment - Unknown",
    amount: -75.0,
    direction: "debit",
    suggestedCategory: "Personal",
    finalCategory: "Personal",
    confidence: 0.32,
    needsReview: true,
    createdAt: "2026-03-10T09:00:00Z",
  },
  {
    id: "txn-20",
    userId: MOCK_USER_ID,
    statementId: "stmt-3",
    accountId: "acct-5",
    propertyId: "prop-3",
    date: "2026-02-22",
    description: "Pedernales Electric Co-op",
    amount: -178.5,
    direction: "debit",
    suggestedCategory: "Utilities",
    finalCategory: "Utilities",
    confidence: 0.91,
    needsReview: false,
    createdAt: "2026-03-10T09:00:00Z",
  },
];

export const categoryBreakdown: CategoryBreakdown[] = [
  { category: "Mortgage", amount: 6150 },
  { category: "Insurance", amount: 189 },
  { category: "Repairs & Maintenance", amount: 825.41 },
  { category: "Utilities", amount: 423.8 },
  { category: "Landscaping", amount: 350 },
  { category: "Property Tax", amount: 1450 },
  { category: "HOA", amount: 275 },
  { category: "Supplies", amount: 129.99 },
  { category: "Personal", amount: 75 },
  { category: "Miscellaneous", amount: 500 },
];

export const monthlySummaries: MonthlySummary[] = [
  { month: "Oct 2025", expenses: 8420, income: 5650 },
  { month: "Nov 2025", expenses: 9150, income: 5650 },
  { month: "Dec 2025", expenses: 8875, income: 5650 },
  { month: "Jan 2026", expenses: 9340, income: 5650 },
  { month: "Feb 2026", expenses: 10368, income: 6650 },
  { month: "Mar 2026", expenses: 8790, income: 5650 },
];

export { EXPENSE_CATEGORIES };

export const MONTHS = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
] as const;

export function getAccountName(accountId: string): string {
  return accounts.find((a) => a.id === accountId)?.name ?? "Unknown Account";
}

export function getPropertyName(propertyId: string): string {
  return properties.find((p) => p.id === propertyId)?.name ?? "Unknown Property";
}

export function formatCurrency(amount: number): string {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
  }).format(amount);
}

export function formatDate(dateStr: string): string {
  return new Date(dateStr).toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  });
}
